### ISSUE TITLE
TV用户，怎么播放自己的阿里云盘中的视频？

### ISSUE THREAD

**Issue by MartinMa-SH** [PizazzGY/TVBox_warehouse#3]
你好，TV用户，使用的FengMi版本的TVBox，已经扫码登录阿里云盘，可以查询到自己的视频，但是使用遥控器点击视频，都会跳到搜索页面，无法直接播放，请问如何解决？

**Comment by PizazzGY** [comment]
设置里关闭聚合搜索

**Comment by MartinMa-SH** [comment]
搞定了，非常感谢！
